trigger:
- main
pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pip install psycopg2-binary
    pip install flask
    pytest
  displayName: 'pytest'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/results.xml'
    testResultsFormat: 'JUnit'